### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by nu8** [malxau/yori#53]
I see that 2 byte characters are currently supported:

https://en.wikipedia.org/wiki/UTF-8

that is, essentially everything up to U+07FF. Example:

# Ç (U+00C7)

You can paste this order enter it with Alt + 128 on Windows, assuming Windows
Terminal is being used. However it seems 3 and 4 byte characters are not
supported. Example:

# ₧ (U+20A7)

with PowerShell, you can paste the character, or on Windows you can enter as
Alt + 158. However Yori does not accept paste or keyboard input of this
character.

**Comment by pyproman** [comment]
Everything is OK on 1.30 on conhost.exe and Windows Terminal:
![a screenshot](https://user-images.githubusercontent.com/45491635/93716373-22665300-fb78-11ea-8bb6-7431f632a775.png "I don't know why Windows Terminal chose to use this title and icon")
Try to update your Yori (with `ypm -u`) and your Windows Terminal.
#### P.S. In conhost.exe, you can see a P instead of ₧, but if you echo the symbol, ₧ is displayed.
##### P.P.S. Try to run ``ycharmap -e utf16 -s `? 0x20A7` -c 1|cut -o 1 -l 1``.
###### P.P.P.S. I can't check Alt+158, as I use a Russian encoding in my system as default.

**Comment by nu8** [comment]
In `pkginfo.ini`, I see this:

~~~
Version=1.30
~~~

and I updated my terminal to this:

https://github.com/microsoft/terminal/releases/tag/v1.3.2382.0

then start `WindowsTerminal.exe`. Then start `yori.exe`. Neither pasting nor
key entry work for `₧ (U+20A7)`.

**Comment by malxau** [comment]
@nu8 Have you tried with conhost?

The `Alt+<n>` logic is implemented as part of Yori, and I'm seeing the desired behavior with conhost as well as WindowsTerminal 1.2.  I haven't tried/installed 1.3 yet.  Which font are you using?  Does it have these glyphs?

@pyproman Nice suggestions, and thanks for helping.  You don't need the `?` though - Yori uses the same number parser everywhere so specifying `0x20a7` directly to charmap will also work.

**Comment by nu8** [comment]
Conhost doesn't even work with PowerShell, in regards to Unicode. I have Windows 10, but maybe I have an older version than you two?

**Comment by malxau** [comment]
I tried this with Windows 8.1 as well as 18363.  Unicode in the UCS-2 sense has been present in NT since its first release; the only real requirement is a font capable of displaying the result, and not all do since the result is an enormous font.  If you're using Windows Terminal, I don't think you really can have an older Windows 10 version (doesn't it require 18362 as a minimum, and 18363 is a facelift only?)

**Comment by nu8** [comment]
@malxau your comments dont make sense to me, as I dont see what difference a font will make.

As I have said, using Windows Terminal with PowerShell produces expected results with `∞ (U+221E)`, so I dont see how a font plays into the situation. Also `ycharmap` is not in the Core package, so I will need to know what package its in, if I am to test it.

**Comment by malxau** [comment]
I am using Lucida Console.  Which font are you using?  There is a difference between our environment that is material here, and it doesn't sound like OS or package versioning.

`ycharmap` is part of `yori-typical`, run `ypm -ri yori-typical` to install it.  Note all it's doing is outputting characters though - pyroman was using it to get the character into the clipboard, which you're saying you've already done.

Fwiw, I pushed commit 6a5a2ef566a1a116611d447a06714f6ef701ce04 which adds support for Alt+U20A7 as an input sequence, to save time on ycharmap/conversions.

**Comment by nu8** [comment]
I am using Cascadia Mono, changing to Lucida Console, the problem remains.

**Comment by malxau** [comment]
This requires tools from `yori-typical`, but what's the output of:
```
echo <alt+158>|iconv -e utf16|hexdump -g2
```
If the character input is working correctly, hexdump should output:
```
C:\>echo ₧|iconv -e utf16|hexdump -g2
00000000`00000000: 20a7 000d 000a                           . ....
```
which would indicate the problem is in the display, since 0x20a7 was input and passed to child processes correctly, even if it was not displayed correctly.  If the output is not 0x20a7, that indicates the problem is with the input.

If the problem is with input, note there are many ways that input can be generated.  Even pasting from the clipboard is interesting in that in Windows 10 I think the default is for the console to handle Ctrl+V and send the result to the application, which is different to having Yori process Ctrl+V and modify its own buffer.  The two should behave identically in theory but they're implemented differently.  This can be modified in the console window properties.  Pasting from the clipboard through the Yori process is nice though in that it's just a sequence of bytes which doesn't depend on any console/keyboard input handling, so being able to verify that the problem still exists after bypassing all console/keyboard logic would be interesting.

Another interesting test (also depending on `yori-typical`) is just:
```
clip -p
```
Which outputs the clipboard contents.  This tests whether the clipboard data can be rendered without depending on any input handling of the console.  Putting these together,
```
clip -p|iconv -e utf16|hexdump -g2
```
can verify that the character in the clipboard is the intended character, regardless of the display.

The best theory that I have right now (and I'm not saying it's a good theory) is that Alt+158 isn't doing the expected thing because it's using CP_OEMCP which is not the "expected" codepage.  If this is true then the clipboard shouldn't have any problem so long as it contains Unicode text, but entering the character using Alt will.  I don't know of a better way in Windows to say "ASCII" though...

**Comment by nu8** [comment]
> This requires tools from `yori-typical`, but what's the output of:
> 
> ```
> echo <alt+158>|iconv -e utf16|hexdump -g2
> ```

It nothing:

~~~
D:\Desktop\yori-core-amd64>echo |iconv -e utf16|hexdump -g2
00000000`00000000: 000d 000a                                ....
~~~

and if I paste in some text, any character in that range is stripped out. So if
I paste `∞ (U+221E)`, I just get this:

~~~
 (U+221E)
~~~

again, pasting or Alt code into PowerShell works as expected.

> If the problem is with input, note there are many ways that input can be
> generated. Even pasting from the clipboard is interesting in that in Windows
> 10 I think the default is for the console to handle Ctrl+V and send the
> result to the application, which is different to having Yori process Ctrl+V
> and modify its own buffer.

Note I am not using Ctrl+V, I am using right click. Thats with the option
QuickEdit Mode. But trying again now with Ctrl+V, the result is the same.

> Another interesting test (also depending on `yori-typical`) is just:
> 
> ```
> clip -p
> ```

I take it you mean `yclip`? If so, yes, that does work. Using `yclip` will print
the problem character.

> ```
> clip -p|iconv -e utf16|hexdump -g2
> ```

If clipboard contains `∞ (U+221E)`, then this is the result:

~~~
00000000`00000000: 221e 0020 0028 0055 002b 0032 0032 0031  ." .(.U.+.2.2.1.
00000000`00000010: 0045 0029                                E.).
~~~

> Alt+158 isn't doing the expected thing because it's using CP_OEMCP which is
> not the "expected" codepage. If this is true then the clipboard shouldn't
> have any problem so long as it contains Unicode text, but entering the
> character using Alt will.

even if that is true, it doesnt explain why pasting fails as well. I wonder if
it has anything to do with `chcp.com`? I know with Command Prompt that was an
issue in the past, but I dont think PowerShell messes with that. At any rate,
here is mine:

~~~
C:\Windows\System32>chcp.com
Active code page: 65001
~~~

Also I am using this, not sure if it matters:

~~~
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage]
"OEMCP"="65001"
~~~

**Comment by malxau** [comment]
> Note I am not using Ctrl+V, I am using right click. Thats with the option
QuickEdit Mode. But trying again now with Ctrl+V, the result is the same.

What I was trying to say is it matters which process is generating the characters.  Both right click and Ctrl+V can be implemented by either the console or the shell.  In this case, turn off QuickEdit and watch what happens.

> it doesnt explain why pasting fails as well

It does actually, because conhost is trying to generate input characters and doing something unexpected.  If Yori handles the clipboard, it appears to work.

> Also I am using this, not sure if it matters:
> ```
> Windows Registry Editor Version 5.00
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage]
> "OEMCP"="65001"
> ```

Yes, that matters.  I thought this was still an experimental feature?  Anyway, from experimenting with it on 19041:

- Yori is using OEMCP to interpret Alt+NNN sequences, so it's generating U+009e.
- Alt+158 in CMD also gets the wrong character.
- Alt+158 in Powershell (tested 5 and 7) gets the wrong character.
- Pasting from the clipboard using conhost to Yori generates no input.  Note that unlike other shells, Yori is trying to get low level keyboard input, which is part of the issue.  Looking under a debugger, all of the information is there, just in a strange way.  The console generates alt-down, then alt-up with the desired character in the character field in a single keystroke.  Normally this is something Yori painfully assembles, as in alt-down, alt-'1', alt-'5', alt-'8', alt-up.  But it should be simple enough to make this work.
- Pasting from the clipboard using Yori's clipboard code (ie., disable quickedit) works fine.
- Pasting from the clipboard to CMD also works, because in that case conhost owns the input processing logic.
- Pasting from the clipboard to Powershell works fine.
- Alt+158 in Windows Terminal appears to do nothing for CMD and PS.  For Yori, it gets the wrong character.
- Right click to paste in Windows Terminal appears to do the right thing for CMD and PS.  For Yori, nothing happens, which appears to be the input issue mentioned above.
- Ctrl+V doesn't work with Yori in Windows Terminal.  It looks like WT is hijacking this specific key combination, and letting other Ctrl keys to the shell.  The issue described above will allow paste to work, since it's generating the same sequences.  Nonetheless, this seems a bit concerning for other things, like yedit, which might have good reason to want to own clipboard pasting.

So, are you saying Alt+158 is generating the desired character in other shells on your system?  That's not what I'm seeing, and I can't see how to do it without effectively overriding system config.  On my system OEMCP was 437, and I can always forcibly use 437, but that seems antisocial.

**Comment by pyproman** [comment]
I have experimented a bit, and here are the results in `conhost.exe`:
Right click does not work with `QuickEdit` on.
Ctrl+Shift+V does not work with `Use Ctrl+Shift+C/V as Copy/Paste`
In other cases, everything is OK.
But, in Windows Terminal, Ctrl+V works fine, but Ctrl+Shift+V does not work.
I don't think this is related to Yori. May be create an issue at [microsoft/terminal](https://github.com/microsoft/terminal)(was mentioned earlier) which contains source code for `conhost.exe` and Windows Terminal?
###### P.S. My Windows version is 18363 (Windows 10 19H2 1909). 2004 is not appearing for me. What's wrong?

**Comment by nu8** [comment]
> What I was trying to say is it matters which process is generating the
> characters. Both right click and Ctrl+V can be implemented by either the
> console or the shell. In this case, turn off QuickEdit and watch what
> happens.

Holy cow, that was it? If I disable QuickEdit, everything works as expected?
What the heck? I wonder why that would matter? Here are my results with
QuickEdit disabled. Input:

# ∞ (U+221E) (Alt + 236)

shell          | terminal         | ctrl v        | right click
---------------|------------------|---------------|---------------------
cmd            | console host     | good          | good if select paste
cmd            | windows terminal | good          | good
powershell 5.1 | console host     | strip unicode | strip unicode
powershell 5.1 | windows terminal | good          | good
powershell 6   | console host     | nothing       | good if select paste
powershell 6   | windows terminal | good          | good
powershell 7   | console host     | good          | good if select paste
powershell 7   | windows terminal | good          | good
yori           | console host     | good          | good
yori           | windows terminal | strip unicode | strip unicode

**Comment by nu8** [comment]
After doing some more testing, it seems QuickEdit is not the issue. It appears
that the order of characters matter. For example, if you put a normal character
right before a Unicode character, it causes breakage is many more cases. Example
two characters:

# !∞

Second character is U+221E (Alt + 236). Result:

shell          | terminal         | ctrl v        | right click
---------------|------------------|---------------|---------------------
cmd            | console host     | good          | good if select paste
cmd            | windows terminal | good          | good
powershell 5.1 | console host     | strip unicode | strip unicode
powershell 5.1 | windows terminal | strip unicode | strip unicode
powershell 6   | console host     | no response   | strip unicode
powershell 6   | windows terminal | strip unicode | strip unicode
powershell 7   | console host     | good          | strip unicode
powershell 7   | windows terminal | strip unicode | strip unicode
powershell 7.1 | console host     | good          | strip unicode
powershell 7.1 | windows terminal | strip unicode | strip unicode
yori           | console host     | good          | good
yori           | windows terminal | strip unicode | strip unicode
yori QE        | console host     | good          | strip unicode
yori QE        | windows terminal | strip unicode | strip unicode

I posted Yori with and without QuickEdit. The others had the same result,
regardless of QuickEdit.

**Comment by pyproman** [comment]
> After doing some more testing, it seems QuickEdit is not the issue. It appears
> that the order of characters matter. For example, if you put a normal character
> right before a Unicode character, it causes breakage in many more cases. Example
> two characters:
> 
> # !∞
> Second character is U+221E (Alt + 236). Result:
> ...
> I posted Yori with and without QuickEdit. The others had the same result,
> regardless of QuickEdit. Based on the success of Yori (and Command Prompt), it
> seems issues need to be filed with both PowerShell and Windows Terminal.

Wow. The PowerShell 5.x and PowerShell Core are using [PSReadLine](https://github.com/microsoft/PSReadLine), so the problem is not PowerShell itself.
###### (It is funny to see how products of Microsoft together are causing issues)

**Comment by nu8** [comment]
https://github.com/dotnet/runtime/issues/38966

**Comment by malxau** [comment]
I pushed commit 370438dd71cc001a634afeed976bf19e03fc9b7f which should allow these characters to be pasted through QuickEdit/Windows Terminal.

@pyproman The software development process works at Microsoft the same as everywhere else.  As far as I know the UTF-8 console is still experimental, and what it means is when people try it they find some strange thing that doesn't work.  None of us on this thread suspected it would break the clipboard (of all things.)  And I think Slackware still asks whether the user wants a UTF-8 console on install, because Linux had transition pain too, it just started a lot earlier.

**Comment by pyproman** [comment]
> I pushed commit [370438d](https://github.com/malxau/yori/commit/370438dd71cc001a634afeed976bf19e03fc9b7f) which should allow these characters to be pasted through QuickEdit/Windows Terminal.
> 
> @pyproman The software development process works at Microsoft the same as everywhere else. As far as I know the UTF-8 console is still experimental, and what it means is when people try it they find some strange thing that doesn't work. None of us on this thread suspected it would break the clipboard (of all things.) And I think Slackware still asks whether the user wants a UTF-8 console on install, because Linux had transition pain too, it just started a lot earlier.

Oh. The UTF-8 console contains other issues with UTF-8: ![glitch echo ₧₧₧](https://user-images.githubusercontent.com/45491635/93851722-5301d600-fcb9-11ea-9679-a3bf4dc4508a.png "A conhost.exe graphical glitch")
And this explains why this setting ![Beta: Use Unicode UTF-8 for worldwide language support](https://user-images.githubusercontent.com/45491635/93852388-9e68b400-fcba-11ea-9355-56684682eef8.png "Beta: Use Unicode UTF-8 for worldwide language support") is still in beta.

**Comment by nu8** [comment]
Ok I will try it again on the next release - I am not able to build as I do not have a Visual Studio environment - thanks

**Comment by pyproman** [comment]
> Ok I will try it again on the next release - I am not able to build as I do not have a Visual Studio environment - thanks

~~Don't forget that you can download daily packages using ypm -download-daily~~
The fix is not in daily packages yet. But, I quickly compiled and tested, and everything is OK - holding <kbd>Alt</kbd> while typing <kbd>U</kbd> and typing codepoint of the char works fine, as pasting it from conhost.exe interface or Windows Terminal.

**Comment by malxau** [comment]
It's in daily packages now.  Please let me know if there are other changes that Yori can make - I don't think the experience here will be "good" for a while, not it's not clear to me that there are further changes that should be made to make it better.

**Comment by nu8** [comment]
any direct link available? I am using this but its old:

http://malsmith.net/download?obj=yori/latest-stable/yori-core-amd64.cab

**Comment by malxau** [comment]
Use latest-daily rather than latest-stable .

**Comment by nu8** [comment]
Using these two characters:

# !∞

Second character is U+221E. Result:

quickedit | terminal         | ctrl v | right click | alt 236
----------|------------------|--------|-------------|--------
no        | console host     | good   | good        | error
no        | windows terminal | good   | good        | good
yes       | console host     | good   | good        | error
yes       | windows terminal | good   | good        | good

Also I just noticed this comment:

> The best theory that I have right now (and I'm not saying it's a good theory)
> is that Alt+158 isn't doing the expected thing because it's using CP_OEMCP
> which is not the "expected" codepage.

I dont think this is the correct logic. Regardless of `CP_OEMCP`,
`Alt + something` should be pulling from Code page 437:

https://wikipedia.org/wiki/Code_page_437

that is how it works with native Windows tools. Similarly, `Alt + 0something`
should pull from Windows-1252:

https://wikipedia.org/wiki/Windows-1252

**Comment by malxau** [comment]
> I dont think this is the correct logic. Regardless of CP_OEMCP,
> Alt + something should be pulling from Code page 437:

> https://wikipedia.org/wiki/Code_page_437

> that is how it works with native Windows tools.

Are you saying that this is the behavior you get from CMD or PS on conhost?  That is not the behavior I am seeing.  Which OS build are you running?

**Comment by nu8** [comment]
its the way its worked since at least Windows 7. Do you have evidence otherwise?

http://www.fileformat.info/tip/microsoft/enter_unicode.htm

**Comment by malxau** [comment]
Windows 7 did not support UTF-8 consoles, so that is quite moot.

What behavior are you seeing with Alt+158 in CMD with CP_OEMCP as 65001?  Is it applying 437, 65001, or something else?

**Comment by nu8** [comment]
Actually you are right. The `Alt + something` seems to break if you change the
code page, even with other Windows tools. The `Alt + 0something` still work
though. For example

# € U+20AC (Alt + 0128)

works with Notepad, Cmd + Conhost and PowerShell + Conhost, but not
Yori + Conhost.

**Comment by malxau** [comment]
As far as I can tell from reading various sources on the Internet, the Alt+nnn keys are using CP_OEMCP, and the Alt+0nnn keys are using the code page matching the current keyboard layout.  This seems a little strange, but at least it means different locales get different extended characters, and it happens to mean that behavior doesn't change if CP_ACP is set to UTF8.  I pushed a change to implement this behavior for Alt+0nnn, and although it wouldn't conform to the rest of Windows, I'm contemplating extending it to use the OEM code page matching the keyboard for Alt+nnn keys too.  This seems a bit strange (since it's ignoring the user's explicit configuration for CP_OEMCP) but happens to provide a consistent experience if that code page is set to CP_UTF8.

But, having spent a bit of time on this, I have to ask: what is the expected benefit of setting CP_OEMCP/CP_ACP to CP_UTF8?  Everything we've discussed in this thread revolves around behavior that changes but is not desired.  What behavior is a user hoping to get from making this change?

**Comment by nu8** [comment]
> But, having spent a bit of time on this, I have to ask: what is the expected
> benefit of setting CP_OEMCP/CP_ACP to CP_UTF8? Everything we've discussed in
> this thread revolves around behavior that changes but is not desired. What
> behavior is a user hoping to get from making this change?

If you dont do this, it causes problems when dealing with Unicode content. For
example, create a file with this content:

~~~
♠
~~~

Result:

~~~
PS C:\> Get-Content a.txt
â™ 
~~~

https://github.com/PowerShell/PowerShell/issues/7233#issuecomment-640067442

**Comment by malxau** [comment]
Thanks.  You probably already know this, but Yori tools interpret data as UTF-8 and output as UTF-16, so this would do what you want, although that obviously doesn't extend to PS.  Dealing with other encodings require a trip through iconv, which as far as I know is the approach Linux takes.
